### ISSUE TITLE
Preparação de ambiente

### ISSUE THREAD

**Issue by brena-cmd** [atlantico-academy/datagearscore#1]
- [x] @brena-cmd 
- [x] @thasamp 
- [x] @vilquer 
- [x] @larryfisherman25 
- [x] @rian-araujo 
- [x] @vitoriatelesm 
- [x] @rodolfoautran

**Comment by brena-cmd** [comment]
oi

**Comment by brena-cmd** [comment]
oi @vilquer como faz isso?

**Comment by vilquer** [comment]
> oi @vilquer como faz isso?

Não sei! Mas é isso o que eu quero aprender!

**Comment by omadson** [comment]
Vou finalizar essa issue!
