### ISSUE TITLE
Organizar recorrência das dailys

### ISSUE THREAD

**Issue by vilquer** [atlantico-academy/datagearscore#4]
Criar lista de e-mails do Grupo (Adicionar comentário)
- [x] @brena-cmd 
- [x] @thasamp 
- [x] @vilquer 
- [x] @larryfisherman25 
- [x] @rian-araujo 
- [x] @vitoriatelesm 
- [x] @rodolfoautran 

Enviar convite de reuniões recorrentes pelo Google Meet.
- [x]  @rian-araujo

**Comment by rian-araujo** [comment]
lembrando que tem esse endereço com os emails dos participantes do bootcamp de ciencia de dados:
https://docs.google.com/spreadsheets/d/17XgiZFWr-p6qx-5rVRzaHMPIQhl5RUxCQ6NArOQ6cKk/edit#gid=0

**Comment by rian-araujo** [comment]
acabei de enviar o link do google meet para incluírem em suas agendas nos emails divulgados, faltou apenas o email do @rodolfoautran .

**Comment by rodolfoautran** [comment]
> acabei de enviar o link do google meet para incluírem em suas agendas nos emails divulgados, faltou apenas o email do @rodolfoautran .

rodolfoautran@gmail.com

**Comment by vilquer** [comment]
> acabei de enviar o link do google meet para incluírem em suas agendas nos emails divulgados, faltou apenas o email do @rodolfoautran .

Poderia enviar novamente... vilquer@gmail.com

**Comment by vilquer** [comment]
@rian-araujo 


Poderia enviar novamente... vilquer@gmail.com

**Comment by rian-araujo** [comment]
Feito! @rodolfoautran e @vilquer

**Comment by omadson** [comment]
Finalizando!
