### ISSUE TITLE
Entendimento de dados

### ISSUE THREAD

**Issue by omadson** [atlantico-academy/datagearscore#5]
A etapa de entendimento dos dados direciona o foco para identificar, coletar e analisar os conjuntos de dados que podem ajudá-lo a cumprir os objetivos do projeto. Esta fase também possui quatro tarefas:

 - [x] **Coletar os dados iniciais**: adquirir os dados necessários e (se necessário) carregá-los em ferramentas de análise.
 - [x] **Descrever os dados**: examinar os dados e documentar suas propriedades superficiais, como formato de dados, número de registros ou identidades de variáveis.
 - [x] **Explorar os dados**: realizar uma análise mais aprofundada nos dados. Consultar, visualizar e identificar relações entre dados e variáveis.
 - [x] **Verificar a qualidade dos dados**: realizar análises a respeito da qualidade dos dados: o quão limpos são? Também é necessário documentar qualquer tipo de problema de qualidade dos dados.

Essa entrega será feita utilizando um notebook com o nome `01 - Exploratory Data Analysis.ipynb`, dentro do diretório `notebooks/`. Tal notebook conterá a descrição dos dados, bem como a Exploração dos mesmos, através da utilização de gráficos e estatísticas descritivas sobre os dados. Além disso, uma análise de qualidade será necessária.

**Comment by rian-araujo** [comment]
Identificado divergência entre a legenda apresentada no repositório dos dados em análise e os dados analisado nos seguintes tópicos:

- TÓPICO                  |    RANGE LEGENDA   |    RANGE DOS DADOS

- Education                |      min: 1   max: 4        |         min: 0    max: 6
- Payments History    |      min: -1   max: 9       |        min: -2    max: 8

*Qual a interpretação a ser tomada quando os valores nos dados não encontram-se na legenda do repositório?

**Comment by vilquer** [comment]
no caso de EDUCATION, na legenda: 
1 = pós-graduação; 2 = universidade; 3 = ensino médio; 4 = outros

dá pra considerar que qualquer coisa diferente de 1, 2, 3 como sendo "outros".

no caso do Payments History: 
a legenda: -1 = pago devidamente; 1 = atraso de um mês; 2 = atraso de dois meses; . . .; 8 = atraso de oito meses; 9 = atraso de nove meses ou mais"

o nosso interesse são os atrasos que teoricamente aumentam o Risco de inadimplência. 
então tudo >= 1 é atraso 
e tudo < 1 está adimplente

**Comment by omadson** [comment]
Vou fechar essa issue, visto que a análise exploratória já foi finalizada.
