### ISSUE TITLE
Análise descritiva da variável sexo, idade e estado civil

### ISSUE THREAD

**Issue by brena-cmd** [atlantico-academy/datagearscore#8]
- [ ] Analisar dados faltantes
- [ ] Conversão das variáveis (precisa converter para algum padrão?)

**Comment by omadson** [comment]
Algum retorno?

**Comment by rodolfoautran** [comment]
> Algum retorno?

A gente juntou todos os insights no Notebook de exploratory_analysis que foi enviado ontem.
